name: Deploy Terraform Versioned

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo with full history and tags
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get all tags
          

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      # 5️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve 

      
